# Generated by Django 4.2 on 2023-05-29 09:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_alter_contributor_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together={('author', 'project')},
        ),
    ]
