# Generated by Django 4.2 on 2023-05-29 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_user_contributor_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together=set(),
        ),
    ]
